"""Initial Migration

Revision ID: e3b4310fb28f
Revises: 
Create Date: 2024-02-14 09:19:59.522657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3b4310fb28f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment',
    sa.Column('assignmentNumber', sa.Integer(), nullable=False),
    sa.Column('assignmentDepartment', sa.String(), nullable=False),
    sa.Column('DepartmentHead', sa.String(), nullable=False),
    sa.Column('Location', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('assignmentNumber'),
    sa.UniqueConstraint('assignmentDepartment'),
    sa.UniqueConstraint('assignmentNumber')
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(), nullable=False),
    sa.Column('LastName', sa.String(), nullable=False),
    sa.Column('IdentificationNumber', sa.Integer(), nullable=False),
    sa.Column('DateOfBirth', sa.DateTime(), nullable=False),
    sa.Column('Contact', sa.Integer(), nullable=False),
    sa.Column('DateOfEmployement', sa.DateTime(), nullable=False),
    sa.Column('DepartmentNumber', sa.Integer(), nullable=False),
    sa.Column('ContractPeriod', sa.Integer(), nullable=False),
    sa.Column('Passport', sa.String(), nullable=False),
    sa.Column('IdCopy', sa.String(), nullable=False),
    sa.Column('ChiefLetter', sa.String(), nullable=False),
    sa.Column('ClearanceLetter', sa.String(), nullable=False),
    sa.Column('Referees', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['DepartmentNumber'], ['assignment.assignmentNumber'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('IdentificationNumber'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee')
    op.drop_table('assignment')
    # ### end Alembic commands ###
